apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: flask_app:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: elasticsearch-pvc
          mountPath: /root/kuberfinal/redis
      volumes:
      - name: elasticsearch-pvc
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
