#here we are specifying the 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.12.2
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: "12345"
        resources:
          limits:
            memory: 4Gi
