version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.12.2
    ports:
      - "9200:9200"
      - "9300:9300"  # Adding the second port mapping as per the Docker run command
    environment:
      - discovery.type=single-node  # Important for single-node setups in Elasticsearch
      - ELASTIC_PASSWORD=12345
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"  # Set Java options if needed for memory management
    deploy:
      resources:
        limits:
          memory: 4G
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=12345
    depends_on:
      - elasticsearch

  flask_app:
    build: "/"
    image: flask_main:v1.0
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - elasticsearch